### ISSUE TITLE
notas sobre latex-markdown

### ISSUE THREAD

**Issue by crguezl** [ULL-MFP-AET-2122/latex-markdown-alejandro-gonzalez-sarasola#1]
@Alex100260076 

El ejemplo está en `practica4.md` es insuficiente.

Debes incluir tabla de contenidos, imágenes, referencias, referencias bibliográficas, etc. para que estuviera mejor

**Comment by Alex100260076** [comment]
Buenos días,

he hecho algunos cambios en el archivo.

Adjunto el enlace.

https://github.com/ULL-MFP-AET-2122/latex-markdown-alejandro-gonzalez-sarasola/blob/main/practica4.procesos.md

Saludos

**Comment by crguezl** [comment]
Mejor! 

Ya tienes esta práctica mucho mejor. .

🎄 🎅 Felices fiestas

Saludos

Casiano
